//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransactService.BankingServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/BankingService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BankingServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DepositAmount", ReplyAction="http://tempuri.org/IService1/DepositAmountResponse")]
        string DepositAmount(double value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DepositAmount", ReplyAction="http://tempuri.org/IService1/DepositAmountResponse")]
        System.Threading.Tasks.Task<string> DepositAmountAsync(double value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WithdrawAmount", ReplyAction="http://tempuri.org/IService1/WithdrawAmountResponse")]
        string WithdrawAmount(double value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WithdrawAmount", ReplyAction="http://tempuri.org/IService1/WithdrawAmountResponse")]
        System.Threading.Tasks.Task<string> WithdrawAmountAsync(double value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ViewAmount", ReplyAction="http://tempuri.org/IService1/ViewAmountResponse")]
        string ViewAmount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ViewAmount", ReplyAction="http://tempuri.org/IService1/ViewAmountResponse")]
        System.Threading.Tasks.Task<string> ViewAmountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AmountCheck", ReplyAction="http://tempuri.org/IService1/AmountCheckResponse")]
        bool AmountCheck(double value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AmountCheck", ReplyAction="http://tempuri.org/IService1/AmountCheckResponse")]
        System.Threading.Tasks.Task<bool> AmountCheckAsync(double value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        TransactService.BankingServiceReference.CompositeType GetDataUsingDataContract(TransactService.BankingServiceReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<TransactService.BankingServiceReference.CompositeType> GetDataUsingDataContractAsync(TransactService.BankingServiceReference.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TransactService.BankingServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TransactService.BankingServiceReference.IService1>, TransactService.BankingServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DepositAmount(double value) {
            return base.Channel.DepositAmount(value);
        }
        
        public System.Threading.Tasks.Task<string> DepositAmountAsync(double value) {
            return base.Channel.DepositAmountAsync(value);
        }
        
        public string WithdrawAmount(double value) {
            return base.Channel.WithdrawAmount(value);
        }
        
        public System.Threading.Tasks.Task<string> WithdrawAmountAsync(double value) {
            return base.Channel.WithdrawAmountAsync(value);
        }
        
        public string ViewAmount() {
            return base.Channel.ViewAmount();
        }
        
        public System.Threading.Tasks.Task<string> ViewAmountAsync() {
            return base.Channel.ViewAmountAsync();
        }
        
        public bool AmountCheck(double value) {
            return base.Channel.AmountCheck(value);
        }
        
        public System.Threading.Tasks.Task<bool> AmountCheckAsync(double value) {
            return base.Channel.AmountCheckAsync(value);
        }
        
        public TransactService.BankingServiceReference.CompositeType GetDataUsingDataContract(TransactService.BankingServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<TransactService.BankingServiceReference.CompositeType> GetDataUsingDataContractAsync(TransactService.BankingServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
